Laptop.brand =Lenovo
Laptop.price = 90000
Laptop.ramCapacity = 16GB
Laptop.hardDiskCapacity = 1TB
Laptop.ssdCapacity = 1TB
Laptop.colour = Moonlight Blue

Manufacture.mid = 1358
Manufacture.companny = BKC Pvt. Ltd.
Manufacture.address = Coimbatore